server:
  host: localhost
  port: 8080
  mode: development

database:
  driver: sqlite3
  path: ./db.sqlite3
  max_connections: 25
  max_idle_connections: 10

auth:
  jwt_secret: your_secret_key
  token_expiry: 24h

storage:
  upload_path: ./uploads
  max_file_size: 10 # MB
